using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace McpIt.Generator;

/// <summary>
/// Emits <c>McpIt.Generated.McpItToolCatalog</c>: one <c>McpToolDescriptor</c> per generated tool,
/// built from the same <see cref="EndpointModel"/>s that drive tool emission so names, verbs and
/// routes always match what <c>tools/list</c> exposes.
/// </summary>
internal static class CatalogEmitter
{
    internal const string HintName = "McpIt.Generated.McpItToolCatalog.g.cs";

    internal static string Emit(IEnumerable<EndpointModel> models)
    {
        // Deterministic order: tool name first, then verb and route as tie-breakers so duplicate
        // names (a user error the MCP SDK reports at runtime) still emit stably.
        var sorted = models
            .OrderBy(m => m.ToolName, StringComparer.Ordinal)
            .ThenBy(m => m.HttpMethod, StringComparer.Ordinal)
            .ThenBy(m => m.RouteTemplate, StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.Append("""
            // <auto-generated/>
            #nullable enable
            namespace McpIt.Generated;

            /// <summary>
            /// Build-time catalog of every [McpTool] in this assembly (controller actions and
            /// minimal-API handlers), used by McpIt for tool ranking, search and discovery documents.
            /// </summary>
            public static class McpItToolCatalog
            {
                /// <summary>All generated MCP tools, sorted by tool name (ordinal).</summary>
                public static global::System.Collections.Generic.IReadOnlyList<global::McpIt.McpToolDescriptor> Tools { get; } = new global::McpIt.McpToolDescriptor[]
                {

            """);

        foreach (var m in sorted)
        {
            sb.Append("        new global::McpIt.McpToolDescriptor(")
              .Append(Lit(m.ToolName)).Append(", ")
              .Append(Lit(m.Title ?? string.Empty)).Append(", ")
              .Append(m.HasDescription ? Lit(ToolDescription(m.Description!)) : "null").Append(", ")
              .Append(Lit(m.HttpMethod)).Append(", ")
              .Append(Lit(m.RouteTemplate)).Append(", ")
              .Append(m.Category is null ? "null" : Lit(m.Category)).Append(", ")
              .Append(StringArray(m.Keywords)).Append(", ")
              .Append(m.Priority.ToString(System.Globalization.CultureInfo.InvariantCulture)).Append(", ")
              .Append(StringArray(m.Parameters.Select(p => p.Name))).Append(", ")
              .Append(m.ReadOnly ? "true" : "false").Append(", ")
              .Append(m.Destructive ? "true" : "false")
              .Append("),\n");
        }

        sb.Append("""
                };
            }

            """);
        return sb.ToString();
    }

    // Mirrors Emitter.Escape's newline folding so the catalog description is byte-for-byte the
    // description the generated tool advertises via [Description].
    private static string ToolDescription(string description) =>
        description.Replace("\r", " ").Replace("\n", " ");

    private static string Lit(string s) => SymbolDisplay.FormatLiteral(s, quote: true);

    private static string StringArray(IEnumerable<string> items)
    {
        var list = items.ToList();
        return list.Count == 0
            ? "global::System.Array.Empty<string>()"
            : "new string[] { " + string.Join(", ", list.Select(Lit)) + " }";
    }
}
