using System.Collections.Generic;
using System.Linq;

namespace McpIt.Generator;

public static class Emitter
{
    public static string Emit(EndpointModel model)
    {
        var genNs = string.IsNullOrEmpty(model.Namespace) ? "Generated" : model.Namespace + ".Generated";
        var description = Escape(model.Description ?? "");
        var title = Escape(model.Title ?? "");

        var paramComments = string.Join("\n", model.Parameters
            .Select(p => $"// param {p.Name} -> ParameterSource.{p.Source}"));

        var routeBuild = BuildRouteExpression(model);
        var queryBuild = BuildQueryExpression(model);
        var bodyObjectBuild = BuildBodyObjectExpression(model);
        var bodyTypeBuild = BuildBodyTypeExpression(model);

        var readOnly = model.ReadOnly ? "true" : "false";
        var destructive = model.Destructive ? "true" : "false";
        var idempotent = model.Idempotent ? "true" : "false";

        var methodBody = BuildMethodBody(model, routeBuild, queryBuild, bodyObjectBuild, bodyTypeBuild);

        return $$"""
            // <auto-generated/>
            #nullable enable
            namespace {{genNs}};

            // route: {{model.RouteTemplate}}
            // verb: "{{model.HttpMethod}}"
            // description: {{description}}
            {{paramComments}}
            [global::ModelContextProtocol.Server.McpServerToolType]
            public static class {{model.GeneratedClassName}}
            {
                [global::ModelContextProtocol.Server.McpServerTool(Name = "{{model.ToolName}}", Title = "{{title}}", ReadOnly = {{readOnly}}, Destructive = {{destructive}}, Idempotent = {{idempotent}}, OpenWorld = false)]
                [global::System.ComponentModel.Description("{{description}}")]
                {{methodBody}}
            }
            """;
    }

    private static string BuildMethodBody(EndpointModel model, string routeBuild, string queryBuild, string bodyObjectBuild, string bodyTypeBuild)
    {
        var allParams = new List<string> { "global::McpIt.IMcpEndpointInvoker invoker" };

        // Scope-gated tools receive IHttpContextAccessor as the second DI parameter so the
        // guard can inspect the caller's ClaimsPrincipal. Tools without RequiredScope get no
        // additional parameter and no guard check -- their emitted code is identical to today.
        if (model.RequiredScope is not null)
            allParams.Add("global::Microsoft.AspNetCore.Http.IHttpContextAccessor httpContextAccessor");

        allParams.AddRange(model.Parameters.Select(p =>
        {
            var decl = $"{p.TypeFullyQualified} {p.Name}";
            if (!string.IsNullOrWhiteSpace(p.Description))
                return $"[global::System.ComponentModel.Description(\"{Escape(p.Description!)}\")] {decl}";
            return decl;
        }));
        allParams.Add("global::System.Threading.CancellationToken cancellationToken = default");
        var paramList = string.Join(",\n            ", allParams);

        // --- Scope-gated path: always async Task<string> ---
        // The guard check returns a string directly; async lets us freely mix the guard's
        // synchronous return with the awaited invoker call, and handles both shaping variants.
        if (model.RequiredScope is not null)
        {
            var escapedScope = Escape(model.RequiredScope);
            var escapedToolName = Escape(model.ToolName);
            string invokeAndReturn;
            if (model.HasOutputShaping)
            {
                var maxLengthExpr = model.OutputMaxLength.HasValue
                    ? model.OutputMaxLength.Value.ToString(System.Globalization.CultureInfo.InvariantCulture)
                    : "null";
                var fieldsExpr = model.OutputFields.Count > 0
                    ? "new string[] { " + string.Join(", ", model.OutputFields.Select(f => "\"" + Escape(f) + "\"")) + " }"
                    : "null";
                var maxItemsExpr = model.OutputMaxItems.HasValue
                    ? model.OutputMaxItems.Value.ToString(System.Globalization.CultureInfo.InvariantCulture)
                    : "null";
                invokeAndReturn =
                    $"var __r = await invoker.InvokeAsync(\"{model.HttpMethod}\", __path, __query, {bodyObjectBuild}, {bodyTypeBuild}, cancellationToken);\n" +
                    $"        return global::McpIt.OutputShaper.Shape(__r, {maxLengthExpr}, {fieldsExpr}, {maxItemsExpr});";
            }
            else
            {
                invokeAndReturn =
                    $"return await invoker.InvokeAsync(\"{model.HttpMethod}\", __path, __query, {bodyObjectBuild}, {bodyTypeBuild}, cancellationToken);";
            }

            return $$"""
                public static async global::System.Threading.Tasks.Task<string> Invoke(
                        {{paramList}})
                    {
                        if (!global::McpIt.McpScopeGuard.HasScope(httpContextAccessor, "{{escapedScope}}"))
                            return global::McpIt.McpScopeGuard.Denied("{{escapedToolName}}", "{{escapedScope}}");
                        string __path = {{routeBuild}};
                        string? __query = {{queryBuild}};
                        {{invokeAndReturn}}
                    }
                """;
        }

        // --- Non-scope-gated path: output shaping variant (async) ---
        if (model.HasOutputShaping)
        {
            var maxLengthExpr = model.OutputMaxLength.HasValue
                ? model.OutputMaxLength.Value.ToString(System.Globalization.CultureInfo.InvariantCulture)
                : "null";
            var fieldsExpr = model.OutputFields.Count > 0
                ? "new string[] { " + string.Join(", ", model.OutputFields.Select(f => "\"" + Escape(f) + "\"")) + " }"
                : "null";
            var maxItemsExpr = model.OutputMaxItems.HasValue
                ? model.OutputMaxItems.Value.ToString(System.Globalization.CultureInfo.InvariantCulture)
                : "null";

            return $$"""
                public static async global::System.Threading.Tasks.Task<string> Invoke(
                        {{paramList}})
                    {
                        string __path = {{routeBuild}};
                        string? __query = {{queryBuild}};
                        var __r = await invoker.InvokeAsync("{{model.HttpMethod}}", __path, __query, {{bodyObjectBuild}}, {{bodyTypeBuild}}, cancellationToken);
                        return global::McpIt.OutputShaper.Shape(__r, {{maxLengthExpr}}, {{fieldsExpr}}, {{maxItemsExpr}});
                    }
                """;
        }

        // --- Non-scope-gated path: plain Task<string> expression body ---
        return $$"""
            public static global::System.Threading.Tasks.Task<string> Invoke(
                    {{paramList}})
                {
                    string __path = {{routeBuild}};
                    string? __query = {{queryBuild}};
                    return invoker.InvokeAsync("{{model.HttpMethod}}", __path, __query, {{bodyObjectBuild}}, {{bodyTypeBuild}}, cancellationToken);
                }
            """;
    }

    private static string BuildRouteExpression(EndpointModel model)
    {
        var template = model.RouteTemplate;
        var routeParams = model.Parameters.Where(p => p.Source == ParameterSource.Route).ToList();
        if (routeParams.Count == 0)
            return $"\"{template}\"";

        // Build the path via string concatenation rather than an interpolated string:
        // a `global::`-qualified call as the first token of an interpolation hole trips the
        // C# parser (CS0103), so we keep the dynamic segments outside any `$"..."`.
        var remaining = template;
        var pieces = new List<string>();
        while (remaining.Length > 0)
        {
            var matched = routeParams
                .Select(p => new { p, idx = remaining.IndexOf("{" + p.Name + "}") })
                .Where(x => x.idx >= 0)
                .OrderBy(x => x.idx)
                .FirstOrDefault();

            if (matched is null)
            {
                pieces.Add("\"" + remaining + "\"");
                break;
            }

            var token = "{" + matched.p.Name + "}";
            var before = remaining.Substring(0, matched.idx);
            if (before.Length > 0)
                pieces.Add("\"" + before + "\"");

            pieces.Add(
                "global::System.Uri.EscapeDataString(global::System.Convert.ToString(" + matched.p.Name +
                ", global::System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty)");

            remaining = remaining.Substring(matched.idx + token.Length);
        }

        return string.Join(" + ", pieces);
    }

    private static string BuildQueryExpression(EndpointModel model)
    {
        var queryParams = model.Parameters.Where(p => p.Source == ParameterSource.Query).ToList();
        if (queryParams.Count == 0) return "null";

        var parts = queryParams.Select(p =>
            $"(({p.Name} is null) ? null : \"{p.Name}=\" + global::System.Uri.EscapeDataString(" +
            $"global::System.Convert.ToString({p.Name}, global::System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty))");

        var arrayExpr = "new string?[] { " + string.Join(", ", parts) + " }";
        return $"global::McpIt.QueryStringBuilder.Build({arrayExpr})";
    }

    // Returns the object-cast body expression, or a typed null when there is no body parameter.
    // The cast to (object?) makes the compiler resolve the correct InvokeAsync overload.
    private static string BuildBodyObjectExpression(EndpointModel model)
    {
        var bodyParam = model.Parameters.FirstOrDefault(p => p.Source == ParameterSource.Body);
        if (bodyParam is null) return "(object?)null";
        return $"(object?){bodyParam.Name}";
    }

    // Returns a typeof() expression for the body parameter's non-nullable type, or a typed null.
    // CRITICAL: trailing '?' is stripped before typeof() to avoid a compile error in user code
    // (e.g. global::My.OrderRequest? -> typeof(global::My.OrderRequest)).
    private static string BuildBodyTypeExpression(EndpointModel model)
    {
        var bodyParam = model.Parameters.FirstOrDefault(p => p.Source == ParameterSource.Body);
        if (bodyParam is null) return "(global::System.Type?)null";
        // Strip trailing nullable annotation so typeof() receives a non-nullable type name.
        var typeName = bodyParam.TypeFullyQualified.TrimEnd('?');
        return $"typeof({typeName})";
    }

    private static string Escape(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", " ").Replace("\n", " ");
}
