using System.Collections.Generic;
using System.Linq;

namespace McpIt.Generator;

public static class Emitter
{
    public static string Emit(EndpointModel model)
    {
        var genNs = string.IsNullOrEmpty(model.Namespace) ? "Generated" : model.Namespace + ".Generated";
        var description = Escape(model.Description ?? "");
        var title = Escape(model.Title ?? "");

        var paramComments = string.Join("\n", model.Parameters
            .Select(p => $"// param {p.Name} -> ParameterSource.{p.Source}"));

        var routeBuild = BuildRouteExpression(model);
        var queryBuild = BuildQueryExpression(model);
        var bodyBuild = BuildBodyExpression(model);

        var readOnly = model.ReadOnly ? "true" : "false";
        var destructive = model.Destructive ? "true" : "false";
        var idempotent = model.Idempotent ? "true" : "false";

        var methodBody = BuildMethodBody(model, routeBuild, queryBuild, bodyBuild);

        return $$"""
            // <auto-generated/>
            #nullable enable
            namespace {{genNs}};

            // route: {{model.RouteTemplate}}
            // verb: "{{model.HttpMethod}}"
            // description: {{description}}
            {{paramComments}}
            [global::ModelContextProtocol.Server.McpServerToolType]
            public static class {{model.GeneratedClassName}}
            {
                [global::ModelContextProtocol.Server.McpServerTool(Name = "{{model.ToolName}}", Title = "{{title}}", ReadOnly = {{readOnly}}, Destructive = {{destructive}}, Idempotent = {{idempotent}}, OpenWorld = false)]
                [global::System.ComponentModel.Description("{{description}}")]
                {{methodBody}}
            }
            """;
    }

    private static string BuildMethodBody(EndpointModel model, string routeBuild, string queryBuild, string bodyBuild)
    {
        var allParams = new List<string> { "global::McpIt.IMcpEndpointInvoker invoker" };
        allParams.AddRange(model.Parameters.Select(p =>
        {
            var decl = $"{p.TypeFullyQualified} {p.Name}";
            if (!string.IsNullOrWhiteSpace(p.Description))
                return $"[global::System.ComponentModel.Description(\"{Escape(p.Description!)}\")] {decl}";
            return decl;
        }));
        allParams.Add("global::System.Threading.CancellationToken cancellationToken = default");
        var paramList = string.Join(",\n            ", allParams);

        if (model.HasOutputShaping)
        {
            var maxLengthExpr = model.OutputMaxLength.HasValue
                ? model.OutputMaxLength.Value.ToString(System.Globalization.CultureInfo.InvariantCulture)
                : "null";
            var fieldsExpr = model.OutputFields.Count > 0
                ? "new string[] { " + string.Join(", ", model.OutputFields.Select(f => "\"" + Escape(f) + "\"")) + " }"
                : "null";
            var maxItemsExpr = model.OutputMaxItems.HasValue
                ? model.OutputMaxItems.Value.ToString(System.Globalization.CultureInfo.InvariantCulture)
                : "null";

            return $$"""
                public static async global::System.Threading.Tasks.Task<string> Invoke(
                        {{paramList}})
                    {
                        string __path = {{routeBuild}};
                        string? __query = {{queryBuild}};
                        string? __body = {{bodyBuild}};
                        var __r = await invoker.InvokeAsync("{{model.HttpMethod}}", __path, __query, __body, cancellationToken);
                        return global::McpIt.OutputShaper.Shape(__r, {{maxLengthExpr}}, {{fieldsExpr}}, {{maxItemsExpr}});
                    }
                """;
        }

        return $$"""
            public static global::System.Threading.Tasks.Task<string> Invoke(
                    {{paramList}})
                {
                    string __path = {{routeBuild}};
                    string? __query = {{queryBuild}};
                    string? __body = {{bodyBuild}};
                    return invoker.InvokeAsync("{{model.HttpMethod}}", __path, __query, __body, cancellationToken);
                }
            """;
    }

    private static string BuildRouteExpression(EndpointModel model)
    {
        var template = model.RouteTemplate;
        var routeParams = model.Parameters.Where(p => p.Source == ParameterSource.Route).ToList();
        if (routeParams.Count == 0)
            return $"\"{template}\"";

        // Build the path via string concatenation rather than an interpolated string:
        // a `global::`-qualified call as the first token of an interpolation hole trips the
        // C# parser (CS0103), so we keep the dynamic segments outside any `$"..."`.
        var remaining = template;
        var pieces = new List<string>();
        while (remaining.Length > 0)
        {
            var matched = routeParams
                .Select(p => new { p, idx = remaining.IndexOf("{" + p.Name + "}") })
                .Where(x => x.idx >= 0)
                .OrderBy(x => x.idx)
                .FirstOrDefault();

            if (matched is null)
            {
                pieces.Add("\"" + remaining + "\"");
                break;
            }

            var token = "{" + matched.p.Name + "}";
            var before = remaining.Substring(0, matched.idx);
            if (before.Length > 0)
                pieces.Add("\"" + before + "\"");

            pieces.Add(
                "global::System.Uri.EscapeDataString(global::System.Convert.ToString(" + matched.p.Name +
                ", global::System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty)");

            remaining = remaining.Substring(matched.idx + token.Length);
        }

        return string.Join(" + ", pieces);
    }

    private static string BuildQueryExpression(EndpointModel model)
    {
        var queryParams = model.Parameters.Where(p => p.Source == ParameterSource.Query).ToList();
        if (queryParams.Count == 0) return "null";

        var parts = queryParams.Select(p =>
            $"(({p.Name} is null) ? null : \"{p.Name}=\" + global::System.Uri.EscapeDataString(" +
            $"global::System.Convert.ToString({p.Name}, global::System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty))");

        var arrayExpr = "new string?[] { " + string.Join(", ", parts) + " }";
        return $"global::McpIt.QueryStringBuilder.Build({arrayExpr})";
    }

    private static string BuildBodyExpression(EndpointModel model)
    {
        var bodyParam = model.Parameters.FirstOrDefault(p => p.Source == ParameterSource.Body);
        if (bodyParam is null) return "null";
        return $"global::System.Text.Json.JsonSerializer.Serialize({bodyParam.Name})";
    }

    private static string Escape(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", " ").Replace("\n", " ");
}
