using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace McpIt.Generator;

/// <summary>
/// Emits the McpIt.Generated.McpItManifest source file from the collected tool manifest entries.
/// </summary>
internal static class ManifestEmitter
{
    internal static string Emit(ImmutableArray<ManifestEntry> entries)
    {
        // Sort by tool name: makes declaration order irrelevant for hash stability.
        var sorted = entries
            .OrderBy(e => e.ToolName, StringComparer.Ordinal)
            .ToList();

        var aggregateHash = ManifestHashing.AggregateHash(sorted);
        var json = BuildJson(sorted, aggregateHash);
        var escapedJson = EscapeCSharpLiteral(json);

        var toolNamesExpr = sorted.Count > 0
            ? "new string[] { " + string.Join(", ", sorted.Select(e => "\"" + EscapeCSharpLiteral(e.ToolName) + "\"")) + " }"
            : "new string[0]";

        return $$"""
            // <auto-generated/>
            #nullable enable
            namespace McpIt.Generated;

            /// <summary>
            /// Build-time snapshot of the MCP tool-manifest surface for all [McpTool]-annotated
            /// methods in this compilation. AggregateHash is a SHA-256 over the sorted tool
            /// fingerprints (name, description, and ordered parameter signatures).
            ///
            /// V1 coverage: tool names are derived via the explicit Name named-arg on [McpTool],
            /// or camelCase of the method name when no explicit name is set. NamePrefix,
            /// API-version suffixes, and minimal-API route-level overrides are NOT applied in v1;
            /// those methods are fingerprinted only by their direct method-level identity.
            /// Compare AggregateHash against a stored approved snapshot in CI to detect
            /// tool-surface drift or poisoning.
            /// </summary>
            public static class McpItManifest
            {
                /// <summary>
                /// Order-independent SHA-256 aggregate over all tool fingerprints. The same set of
                /// [McpTool]-annotated methods always produces the same hash regardless of their
                /// declaration order in source. An empty tool set yields the SHA-256 of an empty string.
                /// </summary>
                public const string AggregateHash = "{{aggregateHash}}";

                /// <summary>
                /// Precomputed JSON manifest as a compile-time string constant. No runtime serialization
                /// is performed; the consumer passes this constant directly to the endpoint helper:
                ///   app.MapMcpManifest(McpIt.Generated.McpItManifest.Json);
                /// Structure: { "aggregateHash": "...", "tools": [{ "name": "...", "hash": "...", "parameterCount": N }] }
                /// </summary>
                public const string Json = "{{escapedJson}}";

                /// <summary>Alphabetically sorted names of all MCP tools in this compilation.</summary>
                public static readonly string[] ToolNames = {{toolNamesExpr}};
            }
            """;
    }

    // Builds the JSON payload. Tool names are JSON-escaped; hashes are hex-only so need no escaping.
    private static string BuildJson(List<ManifestEntry> sorted, string aggregateHash)
    {
        var sb = new StringBuilder();
        sb.Append("{\"aggregateHash\":\"").Append(aggregateHash).Append("\",\"tools\":[");
        for (var i = 0; i < sorted.Count; i++)
        {
            if (i > 0) sb.Append(',');
            var e = sorted[i];
            sb.Append("{\"name\":\"")
              .Append(EscapeJson(e.ToolName))
              .Append("\",\"hash\":\"")
              .Append(ManifestHashing.PerToolHash(e))
              .Append("\",\"parameterCount\":")
              .Append(e.Parameters.Count)
              .Append('}');
        }
        sb.Append("]}");
        return sb.ToString();
    }

    // Escapes a value for embedding inside a C# non-verbatim string literal.
    private static string EscapeCSharpLiteral(string s) =>
        s.Replace("\\", "\\\\")
         .Replace("\"", "\\\"")
         .Replace("\r", "\\r")
         .Replace("\n", "\\n")
         .Replace("\t", "\\t");

    // Escapes a value for safe inclusion as a JSON string value.
    private static string EscapeJson(string s) =>
        s.Replace("\\", "\\\\")
         .Replace("\"", "\\\"")
         .Replace("\r", "\\r")
         .Replace("\n", "\\n")
         .Replace("\t", "\\t");
}
