using System.Linq;
using Microsoft.CodeAnalysis;

namespace McpIt.Generator.Tests;

// McpIt.Generated.McpItToolCatalog: one McpToolDescriptor per generated tool, derived from the
// same EndpointModels as the tools themselves (controller, method-group, MapGroup and lambda).
public class ToolCatalogTests
{
    private const string GenericStub = """

        namespace Microsoft.AspNetCore.Builder
        {
            public interface IEndpointRouteBuilder { }
            public static class MinimalApiStubExtensions
            {
                public static void MapGet<THandler>(this IEndpointRouteBuilder b, string p, THandler h) { }
                public static void MapPost<THandler>(this IEndpointRouteBuilder b, string p, THandler h) { }
                public static void MapDelete<THandler>(this IEndpointRouteBuilder b, string p, THandler h) { }
                public static IEndpointRouteBuilder MapGroup(this IEndpointRouteBuilder b, string prefix) => b;
            }
        }
        """;

    // Delegate-typed stub: the real ASP.NET Core shape, which forces the lambda-from-syntax path.
    private const string DelegateStub = """

        namespace Microsoft.AspNetCore.Builder
        {
            public static class TestWebApp
            {
                public static object MapGet(this object app, string route, System.Delegate handler) => app;
                public static object MapPost(this object app, string route, System.Delegate handler) => app;
            }
        }
        """;

    private static string Catalog(GeneratorResult result)
    {
        var src = result.AllGeneratedSource;
        var start = src.IndexOf("// <auto-generated/>\n#nullable enable\nnamespace McpIt.Generated;", System.StringComparison.Ordinal);
        Assert.True(start >= 0, "McpItToolCatalog was not generated:\n" + src);
        var end = src.IndexOf("\n}\n", start, System.StringComparison.Ordinal);
        return src.Substring(start, end - start + 3);
    }

    private static void AssertCompiles(GeneratorResult result) =>
        Assert.Empty(result.CompilationDiagnostics.Where(d => d.Severity == DiagnosticSeverity.Error));

    [Fact]
    public void Controller_actions_produce_catalog_entries_with_class_category_default()
    {
        var src = """
            using McpIt;
            using Microsoft.AspNetCore.Mvc;
            namespace Demo;

            [Route("api/orders")]
            [McpTool(Category = "orders")]
            public class OrdersController : ControllerBase
            {
                /// <summary>Gets a single order by its identifier.</summary>
                [HttpGet("{id}")]
                [McpTool(Keywords = new[] { "lookup", " find ", "LOOKUP", "" }, Priority = 5)]
                public string GetOrder(int id, string? expand, System.Threading.CancellationToken ct) => "ok";

                /// <summary>Deletes an order permanently from the system.</summary>
                [HttpDelete("{id}")]
                [McpTool(Category = "admin", AllowDestructive = true, Title = "Remove order")]
                public void DeleteOrder(int id) { }
            }
            """;

        var result = GeneratorTestHarness.Run(src);
        AssertCompiles(result);
        var catalog = Catalog(result);

        Assert.Contains("internal static class McpItToolCatalog", catalog);
        Assert.Contains(
            "public static global::System.Collections.Generic.IReadOnlyList<global::McpIt.McpToolDescriptor> Tools { get; } = new global::McpIt.McpToolDescriptor[]",
            catalog);

        // Class-level Category is the default; Keywords are trimmed, de-duplicated (case-insensitive)
        // and blanks dropped; the CancellationToken is not a tool parameter.
        Assert.Contains(
            "new global::McpIt.McpToolDescriptor(\"getOrder\", \"Get Order\", \"Gets a single order by its identifier.\", \"GET\", \"api/orders/{id}\", \"orders\", new string[] { \"lookup\", \"find\" }, 5, new string[] { \"id\", \"expand\" }, true, false),",
            catalog);

        // Action-level Category wins over the class default; explicit Title is used.
        Assert.Contains(
            "new global::McpIt.McpToolDescriptor(\"deleteOrder\", \"Remove order\", \"Deletes an order permanently from the system.\", \"DELETE\", \"api/orders/{id}\", \"admin\", global::System.Array.Empty<string>(), 0, new string[] { \"id\" }, false, true),",
            catalog);
    }

    [Fact]
    public void Controller_without_any_category_emits_null_category_and_description()
    {
        var src = """
            using McpIt;
            using Microsoft.AspNetCore.Mvc;
            namespace Demo;

            [Route("ping")]
            public class PingController : ControllerBase
            {
                [HttpGet]
                [McpTool]
                public string Ping() => "pong";
            }
            """;

        var result = GeneratorTestHarness.Run(src);
        AssertCompiles(result);
        Assert.Contains(
            "new global::McpIt.McpToolDescriptor(\"ping\", \"Ping\", null, \"GET\", \"ping\", null, global::System.Array.Empty<string>(), 0, global::System.Array.Empty<string>(), true, false),",
            Catalog(result));
    }

    [Fact]
    public void Method_group_and_MapGroup_handlers_are_in_the_catalog()
    {
        var src = """
            using McpIt;
            using Microsoft.AspNetCore.Builder;
            namespace Demo
            {
                public static class Handlers
                {
                    /// <summary>Lists every item in the warehouse inventory.</summary>
                    [McpTool(Category = "inventory", Keywords = new[] { "stock" }, Priority = 1)]
                    public static string ListItems(string? filter) => "";

                    /// <summary>Creates a new item in the warehouse inventory.</summary>
                    [McpTool(AllowDestructive = true)]
                    public static string CreateItem(string name) => "";
                }

                public class AppHost
                {
                    public void Register(IEndpointRouteBuilder app)
                    {
                        app.MapGet("/items", Handlers.ListItems);
                        var g = app.MapGroup("/api/v2");
                        g.MapPost("/items", Handlers.CreateItem);
                    }
                }
            }
            """ + GenericStub;

        var result = GeneratorTestHarness.Run(src);
        AssertCompiles(result);
        var catalog = Catalog(result);

        Assert.Contains(
            "new global::McpIt.McpToolDescriptor(\"listItems\", \"List Items\", \"Lists every item in the warehouse inventory.\", \"GET\", \"/items\", \"inventory\", new string[] { \"stock\" }, 1, new string[] { \"filter\" }, true, false),",
            catalog);
        Assert.Contains(
            "new global::McpIt.McpToolDescriptor(\"createItem\", \"Create Item\", \"Creates a new item in the warehouse inventory.\", \"POST\", \"api/v2/items\", null, global::System.Array.Empty<string>(), 0, new string[] { \"name\" }, false, true),",
            catalog);
    }

    [Fact]
    public void Inline_lambda_reads_discoverability_args_from_syntax()
    {
        var src = """
            using McpIt;
            using Microsoft.AspNetCore.Builder;
            namespace Demo
            {
                public class AppHost
                {
                    private const string Syn = "inventory-count";

                    public void Register(object app)
                    {
                        app.MapGet("/stock/{sku}",
                            [McpTool(Name = "getStock", Category = "inventory", Keywords = new string[] { "quantity", Syn }, Priority = -2)]
                            [System.ComponentModel.Description("Returns the stock level for a product SKU.")]
                            (string sku, System.Threading.CancellationToken ct) => sku);
                        app.MapPost("/stock",
                            [McpTool(Name = "addStock", Keywords = ["restock"])]
                            (int amount) => amount);
                    }
                }
            }
            """ + DelegateStub;

        var result = GeneratorTestHarness.Run(src);
        AssertCompiles(result);
        var catalog = Catalog(result);

        // Inline lambdas have no method name to derive a title from, so Title is empty.
        Assert.Contains(
            "new global::McpIt.McpToolDescriptor(\"getStock\", \"\", \"Returns the stock level for a product SKU.\", \"GET\", \"/stock/{sku}\", \"inventory\", new string[] { \"quantity\", \"inventory-count\" }, -2, new string[] { \"sku\" }, true, false),",
            catalog);
        Assert.Contains(
            "new global::McpIt.McpToolDescriptor(\"addStock\", \"\", null, \"POST\", \"/stock\", null, new string[] { \"restock\" }, 0, new string[] { \"amount\" }, false, true),",
            catalog);
    }

    // The pipeline only falls back to BuildFromLambda when Roslyn cannot bind the lambda to a
    // method symbol, which a well-formed test source rarely triggers. Drive it directly so the
    // syntax readers for Category/Keywords/Priority (array forms, consts, negative ints) are covered.
    [Fact]
    public void BuildFromLambda_reads_category_keywords_and_priority_from_attribute_syntax()
    {
        var src = """
            using McpIt;
            namespace Demo
            {
                public class AppHost
                {
                    private const string Syn = "inventory-count";
                    private const int Boost = -3;
                    public void Register()
                    {
                        System.Func<string, string> a =
                            [McpTool(Category = "inventory", Keywords = new[] { "quantity", Syn, "Quantity" }, Priority = Boost)]
                            [System.ComponentModel.Description("Returns the stock level for a SKU.")]
                            (string sku) => sku;
                        System.Func<int, int> b = [McpTool(Keywords = ["restock"], Priority = 7)] (int amount) => amount;
                    }
                }
            }
            """;

        var tree = Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText(src);
        var compilation = Microsoft.CodeAnalysis.CSharp.CSharpCompilation.Create(
            "LambdaSyntax",
            [tree],
            GeneratorTestHarness.FrameworkReferences
                .Cast<MetadataReference>()
                .Append(MetadataReference.CreateFromFile(typeof(McpToolAttribute).Assembly.Location)),
            new Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        var semanticModel = compilation.GetSemanticModel(tree);
        var lambdas = tree.GetRoot().DescendantNodes()
            .OfType<Microsoft.CodeAnalysis.CSharp.Syntax.ParenthesizedLambdaExpressionSyntax>()
            .ToArray();

        var first = ModelBuilder.BuildFromLambda(lambdas[0], "GET", "/stock/{sku}", semanticModel, compilation)!;
        Assert.Equal("inventory", first.Category);
        Assert.Equal(new[] { "quantity", "inventory-count" }, first.Keywords.ToArray());
        Assert.Equal(-3, first.Priority);
        Assert.Equal(new[] { "sku" }, first.UndescribedParameters.ToArray());

        var second = ModelBuilder.BuildFromLambda(lambdas[1], "POST", "/stock", semanticModel, compilation)!;
        Assert.Null(second.Category);
        Assert.Equal(new[] { "restock" }, second.Keywords.ToArray());
        Assert.Equal(7, second.Priority);
    }

    [Fact]
    public void Entries_are_sorted_by_tool_name_ordinal()
    {
        var src = """
            using McpIt;
            using Microsoft.AspNetCore.Mvc;
            namespace Demo;

            [Route("x")]
            public class XController : ControllerBase
            {
                [HttpGet("c")] [McpTool(Name = "charlie")] public string C() => "";
                [HttpGet("a")] [McpTool(Name = "alpha")] public string A() => "";
                [HttpGet("b")] [McpTool(Name = "Bravo")] public string B() => "";
            }
            """;

        var catalog = Catalog(GeneratorTestHarness.Run(src));
        var bravo = catalog.IndexOf("(\"Bravo\"", System.StringComparison.Ordinal);
        var alpha = catalog.IndexOf("(\"alpha\"", System.StringComparison.Ordinal);
        var charlie = catalog.IndexOf("(\"charlie\"", System.StringComparison.Ordinal);

        // Ordinal: uppercase sorts before lowercase.
        Assert.True(bravo >= 0 && bravo < alpha && alpha < charlie, catalog);
    }

    [Fact]
    public void Strings_with_quotes_backslashes_and_newlines_are_escaped()
    {
        var src = """
            using McpIt;
            using Microsoft.AspNetCore.Mvc;
            namespace Demo;

            [Route("files")]
            public class FilesController : ControllerBase
            {
                /// <summary>
                /// Reads a "quoted" file from C:\data\in
                /// and returns its contents.
                /// </summary>
                [HttpGet]
                [McpTool(Category = "a\"b\\c", Keywords = new[] { "tab\there", "line\nbreak" })]
                public string Read(string path) => "";
            }
            """;

        var result = GeneratorTestHarness.Run(src);
        AssertCompiles(result);
        var catalog = Catalog(result);

        // Newlines are folded to spaces exactly as in the tool's own [Description]; the XML
        // summary's inner indentation is kept as-is, so assert around it.
        Assert.Contains("\"Reads a \\\"quoted\\\" file from C:\\\\data\\\\in ", catalog);
        Assert.Contains(" and returns its contents.\"", catalog);
        Assert.DoesNotContain("\\n and returns", catalog);
        Assert.Contains("\"a\\\"b\\\\c\"", catalog);
        Assert.Contains("new string[] { \"tab\\there\", \"line\\nbreak\" }", catalog);
    }

    [Fact]
    public void No_catalog_is_emitted_when_there_are_no_tools()
    {
        // Critical: an empty public catalog would be generated into McpIt.dll itself and collide
        // with every consumer's own McpItToolCatalog (CS0436).
        var src = """
            using Microsoft.AspNetCore.Mvc;
            namespace Demo;

            [Route("plain")]
            public class PlainController : ControllerBase
            {
                [HttpGet] public string Get() => "";
            }
            """;

        var result = GeneratorTestHarness.Run(src);
        Assert.DoesNotContain("McpItToolCatalog", result.AllGeneratedSource);
        Assert.DoesNotContain("McpToolDescriptor", result.AllGeneratedSource);
    }

    [Fact]
    public void Catalog_does_not_change_existing_tool_description_output()
    {
        var src = """
            using McpIt;
            using Microsoft.AspNetCore.Mvc;
            namespace Demo;

            [Route("orders")]
            public class OrdersController : ControllerBase
            {
                /// <summary>Gets a single order by its identifier.</summary>
                [HttpGet("{id}")]
                [McpTool(Keywords = new[] { "lookup" }, Category = "orders", Priority = 3)]
                public string Get(int id) => "";
            }
            """;

        var result = GeneratorTestHarness.Run(src);
        Assert.Contains(
            "[global::System.ComponentModel.Description(\"Gets a single order by its identifier.\")]",
            result.AllGeneratedSource);
        Assert.DoesNotContain("lookup\")]", result.AllGeneratedSource);
    }
}
