using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;

namespace McpIt;

/// <summary>
/// Extension method for serving the precomputed MCP tool-manifest JSON at a dedicated GET endpoint.
/// </summary>
public static class McpManifestEndpoint
{
    /// <summary>
    /// Maps a GET endpoint at <paramref name="pattern"/> that responds 200 with
    /// <c>application/json</c> containing the provided <paramref name="manifestJson"/>.
    /// </summary>
    /// <remarks>
    /// The manifest JSON is a compile-time constant generated by <c>McpManifestGenerator</c>
    /// and available as <c>McpIt.Generated.McpItManifest.Json</c> in the consuming project.
    /// Pass that constant directly:
    /// <code>
    /// app.MapMcpManifest(McpIt.Generated.McpItManifest.Json);
    /// // or with a custom route:
    /// app.MapMcpManifest(McpIt.Generated.McpItManifest.Json, "/api/tool-manifest");
    /// </code>
    /// The endpoint writes the constant string directly with no runtime serialization, making it
    /// fully compatible with Native AOT (no IL2026 / IL3050 usage).
    /// </remarks>
    /// <param name="endpoints">The <see cref="IEndpointRouteBuilder"/> to add the route to.</param>
    /// <param name="manifestJson">
    /// The precomputed manifest JSON. Use <c>McpIt.Generated.McpItManifest.Json</c>.
    /// </param>
    /// <param name="pattern">
    /// The route pattern for the manifest endpoint. Defaults to <c>/mcp/manifest</c>.
    /// </param>
    /// <returns>
    /// An <see cref="IEndpointConventionBuilder"/> that can be used for further configuration
    /// such as adding authorization policies.
    /// </returns>
    public static IEndpointConventionBuilder MapMcpManifest(
        this IEndpointRouteBuilder endpoints,
        string manifestJson,
        string pattern = "/mcp/manifest")
    {
        // Use an explicit RequestDelegate overload to avoid the minimal-API parameter binder,
        // which can involve reflection. Writing a string directly is AOT-clean.
        RequestDelegate handler = ctx =>
        {
            ctx.Response.ContentType = "application/json; charset=utf-8";
            return ctx.Response.WriteAsync(manifestJson, ctx.RequestAborted);
        };

        return endpoints.MapGet(pattern, handler);
    }
}
